### ISSUE TITLE
A little question of paper

### ISSUE THREAD

**Issue by mrluin** [Zj-BinXia/AMSA#3]
Thanks for your great work!

I have a little question about Propagation scheme proposed in your paper.
1. Does the propagation means that further conducting matching between patch in K and corresponding matched patches of K's neighbors in Q?
2. About definition of Q, K, V. I mean that why define feature of reference as Q?

Looking forward to your reply~

**Comment by Zj-BinXia** [comment]
> Thanks for your great work!
> 
> I have a little question about Propagation scheme proposed in your paper.
> 
> 1. Does the propagation means that further conducting matching between patch in K and corresponding matched patches of K's neighbors in Q?
> 2. About definition of Q, K, V. I mean that why define feature of reference as Q?
> 
> Looking forward to your reply~

1. Yes.
2. I follow the previous RefSR work (TTSR, CVPR2020) to define as Q,K,V.  Specifically, the matching process is similar to the non-local attention to aggregate similar information. Our matching process selet the best matched patch, but non-local aggregate the similar patches with softmax.
